#!/bin/bash
set -e

echo "Running dotnet format for MusicoStore.sln..."
dotnet format MusicoStore.sln --no-restore

if [ -n "$(git status --porcelain)" ]; then
  echo "Code was formatted automatically. Adding changes..."
  git add .
fi
